### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by seisdr** [harryi3t/psx-download-helper-nodejs#4]

**Comment by seisdr** [comment]
![IMG_20200317_204834](https://user-images.githubusercontent.com/45742462/76895080-5ea2b900-68a0-11ea-8160-2cdf40c4c2f5.jpg)

**Comment by sachdevnitin19** [comment]
After downloading game files, move the game files to data directory inside the repository.

**Comment by seisdr** [comment]
Never mind I just installed the wrong version
